name: Generate Blogposts JSON

on:
  workflow_dispatch:
  push:
    paths:
      - 'blogposts/**' # Trigger on changes to blogposts directory

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '21'

    - name: Install dependencies
      run: npm install cheerio

    - name: Generate blogposts.json
      run: node js/generate-blogposts-json.js

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add blogposts.json
        git commit -m "Update blogposts.json"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}